Optimize runtime tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -319,52 +319,67 @@ jobs:
     - name: Test via Docker container
       if: steps.build-docker.outcome == 'success'
       run: |
-        docker_host="127.0.0.1:28181"
-        docker_id=$(docker run -d -p 127.0.0.1:28181:28181 --rm -v $GITHUB_WORKSPACE/${SAVED_NAME}:/ci test-container)
+        host_port=28181
+        req_url=http://127.0.0.1:${host_port}
+        webui_port=8080
+        webui_url=http://127.0.0.1:${webui_port}
+        docker_id=$(docker run -d -p 127.0.0.1:${host_port}:${webui_port} --mount type=bind,src=$GITHUB_WORKSPACE/${SAVED_NAME},dst=/ci,readonly test-container)
+        [ -n "${docker_id}" ] || { echo "::error::Can't startup the docker!"; exit 1; }
         end_time=$(($(date +%s) + 200))
         while [ "${end_time}" -gt "$(date +%s)" ]; do
-        	if [ "$( docker container inspect -f '{{.State.Status}}' $docker_id )" = "running" ]; then
-        		[ -f "/tmp/openwrt-${docker_id}.log" ] || docker logs "${docker_id}" -t -f &> /tmp/openwrt-${docker_id}.log &
-        		if [ -n "$(docker exec $docker_id netstat -nl | grep 28181)" ]; then
+        	if [ -n "$(docker ps -f id=${docker_id} -f status=running -q)" ]; then
+        		if [ -n "$(docker exec $docker_id netstat -ntul | grep ${webui_port})" ]; then
         			sid=$(curl -is -m 10 \
-        				-H "Referer: http://${docker_host}" \
+        				-H "Host: ${webui_url}" \
         				-d 'username=admin&password=adminadmin' \
-        				http://${docker_host}/api/v2/auth/login \
+        				${req_url}/api/v2/auth/login \
         				| grep '^set-cookie' | sed -n 's/\S\+ SID=\([^\x0-\x1f ",;\\\x7f]\+\); .*/\1/gp' 2>&1);
         			[ -z "$sid" ] || break;
         		fi
 
         		sleep 1
         	else
-        		echo "::error ::The docker is not running!"
-        		exit 1
+        		echo "::error::The docker is not running!"
+        		break
         	fi
         done
         printf "Startup delay: %ss\n" $((200 + $(date +%s) - ${end_time}))
 
-        if [ -n "$sid" ]; then
-        	echo "::group::qBittorrent info"
-        	echo "-------------------------------------------"
-        	curl -s -m 10 --cookie "SID=${sid}" http://${docker_host}/api/v2/app/version | xargs echo "qBittorrent:"
-        	curl -s -m 10 --cookie "SID=${sid}" http://${docker_host}/api/v2/app/webapiVersion | xargs echo "WebAPI:"
-        	echo "-------------------------------------------"
-        	curl -s -m 10 --cookie "SID=${sid}" http://${docker_host}/api/v2/app/buildInfo | jq -r 'to_entries[] | "\(.key): \(.value)"'
-        	curl -s -m 10 -X POST --cookie "SID=${sid}" http://${docker_host}/api/v2/app/shutdown
-        	echo "::endgroup::"
-        	end_time=$(($(date +%s) + 100))
-        	while [ "${end_time}" -gt "$(date +%s)" ]; do
-        		shotId=$(echo $sid | cut -c 12)
-        		[ -n "$(docker ps --format '{{.ID}}' | grep "${shortId}")" ] && sleep 1 || break;
-        	done
+        if [ -n "$(docker ps -f id=${docker_id} -f status=running -q)" ]; then
+        	if [ -n "$sid" ]; then
+        		echo "::group::qBittorrent info"
+        		echo "-------------------------------------------"
+        		curl -s -m 10 -H "Host: ${webui_url}" --cookie "SID=${sid}" ${req_url}/api/v2/app/version | xargs echo "qBittorrent:"
+        		curl -s -m 10 -H "Host: ${webui_url}" --cookie "SID=${sid}" ${req_url}/api/v2/app/webapiVersion | xargs echo "WebAPI:"
+        		echo "-------------------------------------------"
+        		curl -s -m 10 -H "Host: ${webui_url}" --cookie "SID=${sid}" ${req_url}/api/v2/app/buildInfo | jq -r 'to_entries[] | "\(.key): \(.value)"'
+        		echo "::endgroup::"
+        		echo "::group::qBittorrent logs"
+        		curl -s -m 10 -H "Host: ${webui_url}" --cookie "SID=${sid}" ${req_url}/api/v2/log/main?last_known_id=-1 | jq -r '.[] | "\(.timestamp | todate) \(.message)"'
+        		echo "::endgroup::"
+        		curl -s -m 10 -X POST -H "Host: ${webui_url}" --cookie "SID=${sid}" ${req_url}/api/v2/app/shutdown
+        		end_time=$(($(date +%s) + 100))
+        		while [ "${end_time}" -gt "$(date +%s)" ]; do
+        			[ -n "$(docker ps -f id=${docker_id} -f status=running -q)" ] && sleep 1 || { err_code=0; break; }
+        		done
+        	else
+        		echo "::error::Can't connect to qbittorrent!!!"
+        	fi
+        	[ -z "$(docker ps -f id=${docker_id} -f status=running -q)" ] || { echo "::warning::The docker will be forced to kill!"; docker kill ${docker_id}; }
         fi
 
-        if [ -f "/tmp/openwrt-${docker_id}.log" ]; then
+        log_path=$(docker inspect --format {{.LogPath}} ${docker_id})
+        [ -z "${log_path}" ] || {
         	echo "::group::Docker logs"
-        	cat /tmp/openwrt-${docker_id}.log
+        	## keep six digits
+        	#sudo jq -j '"\(.time | .[0:-1] | [.[0:19], (.[19:] | tonumber * 1e6 | round | tostring | until(length >= 6; "0" + .))] | join("."))Z \(.log)"' "${log_path}"
+        	# Padding zero
+        	sudo jq -j '"\(.time | .[0:-1] | until(length >= 29; . + "0"))Z \(.log)"' "${log_path}"
         	echo "::endgroup::"
-        fi
+        }
+        docker rm -f "${docker_id}"
 
-        [ -n "$sid" ] || { echo "Can't connect to qbittorrent!!!"; exit 1; }
+        exit ${err_code:-1}
   pre-release:
     if: needs.build-prep.outputs.draft == 'success'
     needs: [build-prep, build-matrix]
